telegram:
  bot_id: "6621115120:AAGbttFrh_3ZjTl7YkUFpHaFZVj0kZnIXMc"
  chat_id: 
    - "773077583"

scraper:
  wait_time_min: 5
  date: "21.07.2025" # Date before which search for exam

admin:
  password: "test"